# -*- coding: utf-8 -*-
"""make_appendix.py —— 生成 paper/appendix.tex（附录 A：全量数字）。

原则：**表里的数字一律从产物读出来，不手抄**；只有已经登记在 Claims_Ledger 里的
派生量（预筛混淆矩阵）才按登记值写，并在 LaTeX 注释里标明出处。
"""
import json
import os
from pathlib import Path

R = Path(os.path.dirname(os.path.abspath(__file__)))
PAPER = R.parent / "paper"
OUT = PAPER / "appendix.tex"

# B 线 v2：8B 是参考模型，目录不带后缀
BLINE = [("Qwen3-0.6B", "_06b", "pilot_Qwen3-0.6B_"),
         ("Qwen3-1.7B", "_17b", "pilot_Qwen3-1.7B_"),
         ("Qwen3-4B", "_4b", "pilot_Qwen3-4B_"),
         ("Qwen3-4B-Instruct", "_4bi", "pilot_Qwen3-4B-Instruct_"),
         ("Qwen3-8B", "", "pilot_Qwen3-8B_"),
         ("Qwen3.5-4B-Base", "_q35", "pilot_Qwen_Qwen3.5-4B-Base_")]
HOTPOT = [("Qwen3-0.6B", "out_s6_hotpot_fix_06b", "pilot_Qwen3-0.6B_"),
          ("Qwen3-1.7B", "out_s6_hotpot_fix_17b", "pilot_Qwen3-1.7B_"),
          ("Qwen3-8B", "out_s6_hotpot_fix_8b", "pilot_Qwen3-8B_"),
          ("Qwen3-4B", "out_s6_hotpot_fix_4b", "pilot_Qwen3-4B_"),
          ("Qwen3.5-4B-Base", "out_s6_hotpot_fix_q35_4b", "pilot_Qwen_Qwen3.5-4B-Base_")]
# 只在产物存在时才纳入（0.6B/1.7B 是第三轮补跑，未跑完不影响生成）
HOTPOT = [t for t in HOTPOT if (R / t[1]).is_dir()]


def metrics(d, nf):
    p = R / d / (nf + "metrics.json")
    with open(p, encoding="utf-8") as f:
        return json.load(f)


# B 线逐格 masking 的 95% CI：读 analyze_kaxis 产物，masking CI = 反射后的 DiD CI
ANALYSIS = {"Qwen3-0.6B": "q3_06b", "Qwen3-1.7B": "q3_17b", "Qwen3-4B": "q3_4b",
            "Qwen3-4B-Instruct": "q3_4bi", "Qwen3-8B": "q3_8b",
            "Qwen3.5-4B-Base": "q35_4b"}


def masking_ci(model, k):
    with open(R / ("out_b8_fix_analysis_%s.json" % ANALYSIS[model]), encoding="utf-8") as f:
        j = json.load(f)
    lo, hi = j["per_k"]["k=%d" % k]["all"]["did_ci"]
    return -hi, -lo


# 第二轮离线分析产物（v2 清洗消融 / 题级条件分析 / 选型翻转）
try:
    R2 = json.loads((R / "out_review_round2.json").read_text(encoding="utf-8"))
except FileNotFoundError:
    R2 = {"cleaning": {}, "conditional": {}, "selection_flip": {}}


def m3(x):
    return "%.3f" % x


def ms3(x):
    return "%+.3f" % x


L = []
A = L.append

A(r"% ============================================================================")
A(r"%  Appendix A --- generated by rag_leak/make_appendix.py. Do not edit by hand.")
A(r"%  Sources: rag_leak/out_*/metrics.json, fourarm.jsonl, out_sensitivity.json,")
A(r"%           anno_defects_90.json, out_b8_audit_summary.json")
A(r"%  NOTE: tables are deliberately NON-floating (captionof + center), because floating")
A(r"%        them lets LaTeX drift a table past its own heading and leave the heading bare.")
A(r"% ============================================================================")
A(r"\section{Full numbers}")
A(r"\label{app:full}")
A("")
A(r"This appendix reports the numbers behind every figure and table in the main text. "
  r"All of them are read directly from the per-question artifacts accompanying this paper.")
A("")

# 中文枚举值 -> 英文（产物里的 scope/tag 是中文，不能直接进英文论文，也不能进 pdflatex）
SCOPE_EN = {"全量": "all items", "人审抽样": "audited sample", "剔坏样本": "after removing flagged"}


def tag_en(t):
    if t == "全部":
        return "none (all models)"
    if t.startswith("剔除 "):
        return "drop " + t[len("剔除 "):]
    return t


# ---------------- A.1 B 线四臂 ----------------
A(r"\subsection{B-line: four arms, six models, both depths}")
A(r"\begin{center}\small")
A(r"\captionof{table}{TriviaQA B-line, final construction (v2), $n{=}432$ questions per cell, "
  r"shared-corpus BM25 retrieval. Each row is one model at one depth; $a/b/c/d$ are the "
  r"four arm accuracies and $\mask=(a-c)-(b-d)$. The interval is the paired-bootstrap "
  r"interval for masking, so the ``10 of 12'' claim in the abstract can be checked row by "
  r"row: only the 0.6B model's two intervals touch zero.}")
A(r"\label{tab:app-bline}")
A(r"\begin{tabular}{llrrrrr}")
A(r"\toprule")
A(r"Model & $k$ & $a$ & $b$ & $c$ & $d$ & \mask\ (95\% CI) \\")
A(r"\midrule")
for name, suf, nf in BLINE:
    for k in (1, 5):
        j = metrics("out_b8_fix_k%d%s" % (k, suf), nf)
        mk = (j["a"] - j["c"]) - (j["b"] - j["d"])
        clo, chi = masking_ci(name, k)
        A(r"%s & %d & %s & %s & %s & %s & %s [%s, %s] \\"
          % (name, k, m3(j["a"]), m3(j["b"]), m3(j["c"]), m3(j["d"]),
             ms3(mk), ms3(clo), ms3(chi)))
    if name != BLINE[-1][0]:
        A(r"\midrule")
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.2 HotpotQA 四臂 ----------------
A(r"\subsection{HotpotQA: four arms and the gate}")
# gate drop 是**聚合差**，聚合为 0 不一定代表"什么都没变"：逐题不一致但两个方向恰好抵消时也会是 0。
# 实测 Qwen3-0.6B 与 Qwen3-4B 就是这种相抵（各题集方向数完全相等）⇒ 表注必须写明，
# 否则读者会把 0.0% 读成"替换没有改变任何题"，那是错的。
_dis = {}
for name, d, nf in HOTPOT:
    _p = R / d / (nf + "oracle_rows.jsonl")
    if _p.is_file():
        _rows = [json.loads(x) for x in _p.read_text(encoding="utf-8").splitlines() if x.strip()]
        _up = sum(1 for r in _rows if r["em_sub"] == 1 and r["em_orig"] == 0)
        _dn = sum(1 for r in _rows if r["em_orig"] == 1 and r["em_sub"] == 0)
        _dis[name] = (_up + _dn, len(_rows), _up == _dn)
_cancel = ", ".join("%s (%d/%d items)" % (n, c[0], c[1]) for n, c in _dis.items() if c[0])
_bal = " and ".join(n for n, c in _dis.items() if c[0] and c[2])
A(r"\begin{center}\small")
A(r"\captionof{table}{HotpotQA C-line, final construction (v2), $n{=}393$, context budget 4096. "
  r"The last column is the oracle-answerability gate of \S\ref{sec:gate3}: the drop in "
  r"accuracy between the original and substituted gold evidence. The frozen thresholds are "
  r"$\leq 3\%$ GO, $\leq 8\%$ REVISE, $>8\%$ ABANDON. The drop is an \emph{aggregate} "
  r"difference, so a value of $0.0\%$ can arise from cancellation rather than from the "
  r"substitution changing nothing: the two arms disagree item by item on " + _cancel +
  r"; for " + _bal + r" these disagreements are exactly balanced, which is what makes the "
  r"aggregate drop zero there.}")
A(r"\label{tab:app-hotpot}")
A(r"\begin{tabular}{lrrrrrr}")
A(r"\toprule")
A(r"Model & $a$ & $b$ & $c$ & $d$ & \mask & gate drop \\")
A(r"\midrule")
for name, d, nf in HOTPOT:
    j = metrics(d, nf)
    mk = (j["a"] - j["c"]) - (j["b"] - j["d"])
    drop = j["oracle_em_orig"] - j["oracle_em_sub"]
    A(r"%s & %s & %s & %s & %s & %s & %.1f\%% \\" % (name, m3(j["a"]), m3(j["b"]), m3(j["c"]),
                                                      m3(j["d"]), ms3(mk), drop * 100))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.3 切分敏感性 ----------------
sens = json.loads((R / "out_sensitivity.json").read_text(encoding="utf-8"))
A(r"\subsection{Sensitivity of the compliance-stratum result to the cut}")
A(r"\begin{center}\small")
A(r"\captionof{table}{Paired $k{=}5$ minus $k{=}1$ difference in corrected gain under two nested "
  r"definitions of the stratum. \emph{Broad} requires only that the planted value occurs in "
  r"the retrieved context; \emph{strict} additionally requires that the model adopted it "
  r"(the two stricter subsets we computed coincide exactly, so they are reported once). "
  r"Signs are negative in all 12 cells; significance is confined to the strict cut.}")
A(r"\label{tab:sens}")
A(r"\begin{tabular}{lrrrr}")
A(r"\toprule")
A(r" & \multicolumn{2}{c}{broad} & \multicolumn{2}{c}{strict} \\")
A(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}")
A(r"Model & $n$ & $\Delta$ (95\% CI) & $n$ & $\Delta$ (95\% CI) \\")
A(r"\midrule")
for name, _, _ in BLINE:
    b = sens["sensitivity"][name]["structural_term_present"]
    s = sens["sensitivity"][name]["term_present_compliance_new"]
    A(r"%s & %d & %s [%s, %s] & %d & %s [%s, %s] \\"
      % (name, b["n"], ms3(b["delta"]), ms3(b["ci"][0]), ms3(b["ci"][1]),
         s["n"], ms3(s["delta"]), ms3(s["ci"][0]), ms3(s["ci"][1])))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")
A(r"\noindent Leave-one-model-out on the pooled strict stratum (1138 item-level "
  r"differences): dropping any single model leaves the pooled $\Delta$ between $-0.12$ and "
  r"$-0.16$, with every interval excluding zero (Table~\ref{tab:app-loo}).")
A("")
A(r"\begin{center}\small")
A(r"\captionof{table}{Pooled strict-stratum difference with each model dropped in turn.}")
A(r"\label{tab:app-loo}")
A(r"\begin{tabular}{lrrr}")
A(r"\toprule")
A(r"Dropped & $n$ & $\Delta$ & 95\% CI \\")
A(r"\midrule")
for tag, v in sens.get("leave_one_out", {}).items():
    A(r"%s & %d & %s & [%s, %s] \\" % (tag_en(tag), v["n"], ms3(v["delta"]),
                                       ms3(v["ci"][0]), ms3(v["ci"][1])))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.4 聚类 bootstrap ----------------
A(r"\subsection{Clustered bootstrap over borrowed values}")
A(r"\begin{center}\small")
A(r"\captionof{table}{Primary stratum contrast with two resampling schemes. The same planted value "
  r"can recur across items, so we also resample whole values (clusters) rather than "
  r"questions. No conclusion changes; the largest interval movement is $0.015$.}")
A(r"\label{tab:cluster}")
A(r"\begin{tabular}{lrrrrr}")
A(r"\toprule")
A(r"Model & items & clusters & $\Delta$ & CI (by item) & CI (by value) \\")
A(r"\midrule")
for name, _, _ in BLINE:
    c = sens["cluster"][name]
    A(r"%s & %d & %d & %s & [%s, %s] & [%s, %s] \\"
      % (name, c["n_items"], c["n_clusters"], ms3(c["delta"]),
         ms3(c["ci_item"][0]), ms3(c["ci_item"][1]),
         ms3(c["ci_cluster"][0]), ms3(c["ci_cluster"][1])))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.5 审计逐条 ----------------
d90 = json.loads((R / "anno_defects_90.json").read_text(encoding="utf-8"))
CAT = [("改错位置", "wrong position"), ("形式坏", "malformed value"),
       ("新值即真答案", "new = true answer"), ("新值自相矛盾", "self-contradictory")]
FLAG = {"甲乙": "both", "甲": "one", "乙": "one", "两人均漏判": "missed by both"}
A(r"\subsection{The audited defects, item by item}")
A(r"\begin{center}\small")
A(r"\captionof{table}{All 22 items judged invalid in the 90-item audit. Indices are the audit's "
  r"own; ``flagged'' records which annotator(s) caught the item, so the two "
  r"both-missed cases are visible. The four classes map onto the three root causes of "
  r"\S\ref{sec:validity} as described there.}")
A(r"\label{tab:app-audit}")
A(r"\begin{tabular}{rlrl}")
A(r"\toprule")
A(r"\# & item & class & flagged \\")
A(r"\midrule")
for it in d90["defects"]:
    raw = it["class"]
    cls = next((en for zh, en in CAT if raw.startswith(zh)), raw[:24])
    A(r"%d & \texttt{%s} & %s & %s \\" % (it["anno_index"], it["task_id"], cls,
                                          FLAG.get(it["flagged_by"], "one")))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.6 预筛混淆矩阵 ----------------
A(r"\subsection{The LLM pre-screen is a weak filter}")
A(r"On the 90 audited items the span-verification probe recovers 10 of the 22 defects "
  r"while flagging 3 of the 68 usable items (Table~\ref{tab:app-prescreen}). Applied to the "
  r"whole 446-item list it flags 43, at a rate that matches between the audited sample "
  r"(11.1\%) and the rest (9.3\%).")
A("")
A(r"\begin{center}\small")
A(r"\captionof{table}{LLM span-verification probe against the human audit ($n{=}90$).}")
A(r"\label{tab:app-prescreen}")
A(r"\begin{tabular}{lrr}")
A(r"\toprule")
A(r" & flagged invalid & judged valid \\")
A(r"\midrule")
A(r"human: invalid & 10 & 12 \\")
A(r"human: valid & 3 & 65 \\")
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.7 清洗消融 ----------------
aud = json.loads((R / "out_b8_audit_summary.json").read_text(encoding="utf-8"))
A(r"\subsection{Cleaning ablations}")
A(r"\begin{center}\small")
A(r"\captionof{table}{Recomputing the decision-axis contrast after removing flagged items. "
  r"Every cell keeps its sign; the effect is diluted by the bad items rather than created "
  r"by them. Computed on the pre-fix (v0) corpus, which is why the levels differ from the "
  r"v2 numbers in the main text.}")
A(r"\label{tab:app-cleaning-v0}")
A(r"\begin{tabular}{llrrrr}")
A(r"\toprule")
A(r"Model & scope & $n$ & \mask($k{=}1$) & \mask($k{=}5$) & $\Delta$masking (95\% CI) \\")
A(r"\midrule")
for r in aud["scope_table"]:
    A(r"%s & %s & %d & %s & %s & %s [%s, %s] \\"
      % (r["model"], SCOPE_EN.get(r["scope"], r["scope"]), r["n"],
         m3(r["masking_k1"]), m3(r["masking_k5"]),
         ms3(r["delta_masking"]), ms3(r["delta_masking_ci"][0]), ms3(r["delta_masking_ci"][1])))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- 附录：TriviaQA 的 gate③ ----------------
A(r"\subsection{The oracle-answerability gate on TriviaQA}")
A(r"\begin{center}\small")
A(r"\captionof{table}{TriviaQA C-line, final construction (v2), $n{=}432$. The gate never "
  r"turns GO here, which is the point of \S\ref{sec:gate3}: on our reading the residual drop "
  r"is the treatment effect rather than a defect in the evidence.}")
A(r"\label{tab:app-trivia-gate}")
A(r"\begin{tabular}{lrrr}")
A(r"\toprule")
A(r"Model & oracle (original) & oracle (substituted) & drop \\")
A(r"\midrule")
for _nm, _suf, _nf in [("Qwen3-0.6B", "_06b", "pilot_Qwen3-0.6B_"),
                       ("Qwen3-1.7B", "_17b", "pilot_Qwen3-1.7B_"),
                       ("Qwen3-4B", "_4b", "pilot_Qwen3-4B_"),
                       ("Qwen3-4B-Instruct", "_4bi", "pilot_Qwen3-4B-Instruct_"),
                       ("Qwen3-8B", "_8b", "pilot_Qwen3-8B_")]:
    j = metrics("out_s6_trivia_fix%s" % _suf, _nf)
    o, s = j["oracle_em_orig"], j["oracle_em_sub"]
    A(r"%s & %s & %s & %.1f\%% \\" % (_nm, m3(o), m3(s), (o - s) * 100))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.8 清洗后重算（v2，全模型） ----------------
A(r"\subsection{Cleaning the fixed corpus, every model}")
A(r"\begin{center}\small")
A(r"\captionof{table}{Every run recomputed with the audited items removed: the union of "
  r"the 22 human-judged invalid and the 43 model-flagged items is 56 distinct items, of "
  r"which \textbf{49 lie in the fixed (v2) corpus} and 7 were already dropped by the fixes "
  r"recorded in \S\ref{sec:validity}; the HotpotQA rows lose none, because the audit was "
  r"drawn from the TriviaQA pool. All 20 cells keep their sign "
  r"and their significance; masking moves slightly upward, i.e.\ the invalid items dilute "
  r"the effect rather than create it. The unchanged HotpotQA rows are therefore not "
  r"evidence of robustness.}")
A(r"\label{tab:app-cleaning}")
A(r"\begin{tabular}{lrrrrr}")
A(r"\toprule")
A(r"Run & $n$ & $n$ (cleaned) & \mask & \mask\ (cleaned) & sign/significance \\")
A(r"\midrule")
_cl = R2.get("cleaning", {})
for _key in sorted(_cl):
    _v = _cl[_key]
    A(r"%s & %d & %d & %s & %s & %s \\"
      % (_key.replace("_", " "), _v["n"], _v["n"] - _v["removed"],
         ms3(_v["masking"]), ms3(_v["masking_clean"]),
         "unchanged" if (_v["sig"] == _v["sig_clean"]) else "CHANGED"))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.9 题级条件分析 ----------------
A(r"\subsection{The identity, seen item by item}")
A(r"\begin{center}\small")
A(r"\captionof{table}{Each run's items split by whether the model answered correctly "
  r"closed-book. Masking is positive on the questions the model already knew and slightly "
  r"negative elsewhere. The gap between strata is bounded near $1$ by construction, because "
  r"$a$ differs by exactly $1$ between them; we report this as an illustration of the "
  r"identity, not as independent evidence.}")
A(r"\label{tab:app-conditional}")
A(r"\begin{tabular}{lrrrr}")
A(r"\toprule")
A(r"Run & $n$ ($a{=}1$) & \mask\ ($a{=}1$) & $n$ ($a{=}0$) & \mask\ ($a{=}0$) \\")
A(r"\midrule")
_cd = R2.get("conditional", {})
for _key in sorted(_cd):
    _v = _cd[_key]
    A(r"%s & %d & %s & %d & %s \\"
      % (_key.replace("_", " "), _v["n_a1"], ms3(_v["masking_a1"]),
         _v["n_a0"], ms3(_v["masking_a0"])))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
A("")

# ---------------- A.10 B 线 k 轴五档（v2，Qwen3-8B） ----------------
# 为什么单列一张表：这一格把"k∈{3,10,20} 只有 v0 的 148 题 pilot"这条 limitation
# 升级成"v2 语料 432 题、五档全跑"。数字来自 analyze_kaxis.py 的产物，不手抄。
_k5 = json.loads((R / "out_b8_fix_kaxis_analysis.json").read_text(encoding="utf-8"))
A(r"\subsection{B-line $k$ axis on the final corpus (five depths)}")
A(r"\begin{center}\small")
A(r"\captionof{table}{B-line $k$ axis for Qwen3-8B on the fixed corpus ($n{=}432$). The corpus is "
  r"identical across depths (closed-book arms are bit-identical item by item), so the only "
  r"difference is how much context retrieval supplies. $\Delta$ is paired against $k{=}1$ with "
  r"an item bootstrap; the interval for $\Delta\mask$ excludes zero at every depth above "
  r"$k{=}1$. The last two columns are from the five-way argmax resampling of "
  r"\S\ref{sec:decision}.}")
A(r"\label{tab:app-kaxis5}")
A(r"\begin{tabular}{rrrrrrrr}")
A(r"\toprule")
A(r"$k$ & $a$ & apparent & corrected & \mask & $\Delta$\mask\ (95\% CI) & $\Delta$apparent & $\Delta$corrected \\")
A(r"\midrule")
_pk = _k5.get("per_k", {})
for _k in (1, 3, 5, 10, 20):
    _b = _pk.get("k=%d" % _k, {}).get("all")
    if not _b:
        continue
    if _k == 1:
        A(r"%d & %s & %s & %s & %s & --- & --- & --- \\"
          % (_k, m3(_b["a"]), ms3(_b["apparent_gain"]), ms3(_b["corrected_gain"]), ms3(_b["masking"])))
    else:
        _p = _k5.get("paired_vs_k1", {}).get("k=%d" % _k, {})
        _dm = _p.get("delta_masking", {})
        _ci = _dm.get("ci") or [float("nan"), float("nan")]
        A(r"%d & %s & %s & %s & %s & $%s$ $[%s,%s]$ & %s & %s \\"
          % (_k, m3(_b["a"]), ms3(_b["apparent_gain"]), ms3(_b["corrected_gain"]), ms3(_b["masking"]),
             ms3(_dm.get("mean")), ms3(_ci[0]), ms3(_ci[1]),
             ms3(_p.get("delta_apparent", {}).get("mean")),
             ms3(_p.get("delta_corrected", {}).get("mean"))))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\end{center}")
_am = _k5.get("argmax", {})
A(r"Five-way argmax: apparent prefers $%s$, corrected prefers $%s$; the argmax changes in "
  r"$%.3f$ of resamples (threshold $0.80$), but the pre-registered rule still returns ``do not "
  r"change'' because the two competing corrected-gain intervals overlap."
  % (_am.get("apparent", {}).get("argmax", "?"), _am.get("corrected", {}).get("argmax", "?"),
     _am.get("p_flip_all_ks", float("nan"))))
A("")

# ---------------- A.11 披露清单 ----------------
A(r"\subsection{Disclosures}")
A(r"\begin{itemize}\itemsep1pt")
for t in [
    r"Agreement is reported under both readings ($\kappa{=}0.82$ and $0.78$); four items "
    r"were decided only after the annotators conferred, which compromises their "
    r"independence.",
    r"The cross-generation check compares models run under two library stacks "
    r"(transformers 4.51.3 and 5.17.0), and Qwen3.5-4B-Base is a vision-language "
    r"architecture, so that comparison is not modality-matched.",
    r"The oracle-answerability gate still returns ABANDON on TriviaQA; our reading of the "
    r"residual as genuine memory resistance is an interpretation, not a measurement.",
    r"Three corpus versions exist (v0, v1, v2); every headline number is from v2, and the "
    r"cross-generation contrast in \S\ref{sec:precond} is drawn from v2 artifacts.",
    r"The audit covers 20.2\% of the construction list; we do not extrapolate beyond the "
    r"corpus-level rate estimate.",
    r"The compliance stratum is a post-hoc cut; see the sensitivity analysis above.",
    r"On the pre-fix corpus 1.7B showed more masking than 4B; on the fixed corpus that "
    r"reversal is gone and the step moves by $+0.065$ (95\% CI $[+0.019,+0.111]$). Neither "
    r"corpus shows the reversal individually, so we report the movement, not a reversal.",
    r"All runs use 4-bit quantisation, which we did not ablate.",
    r"Borrowed values can recur across items; the clustered bootstrap above addresses this "
    r"and changes no conclusion.",
    r"One pipeline run stored its oracle fields under an earlier scorer; every number here "
    r"was recomputed offline with the frozen v3 scorer instead.",
    r"Code, corpora and audit materials: \url{https://anonymous.4open.science/r/ragmask-9c41d7b/}.",
    r"HotpotQA contains no single-hop sub-population, so the multi-hop result cannot be "
    r"explained by a subset of single-hop questions.",
    r"Environment and seeds, for reproduction: a single NVIDIA RTX 4060 Laptop GPU with "
    r"8\,GB, 4-bit weights via bitsandbytes 0.45.5, PyTorch 2.5.1+cu121 (CUDA 12.1), "
    r"transformers 4.51.3 for the Qwen3 family and 5.17.0 for Qwen3.5-4B-Base. Question "
    r"sampling from each pool and every bootstrap use the same fixed seed, 20260903 "
    r"($B{=}10{,}000$ resamples); the sampling seed makes each compared pair of conditions "
    r"see an identical item set, which we verify rather than assume.",
    r"The entity experiment (\S\ref{sec:entity}) additionally discloses that its "
    r"closed-book arm is scored against a single canonical key while the original-answer "
    r"arms use the full answer list, and that this asymmetry biases the entity-line masking "
    r"downward---i.e.\ in the direction of the null reported there.",
]:
    A(r"\item %s" % t)
A(r"\end{itemize}")

# ---------------- 后处理：让长表无法跨页断开 ----------------
# 为什么需要：附录里的表是 `center` + 裸 `tabular`（不是 float、也不是 longtable），
# 而 LaTeX 的裸 tabular **可以**在分页处断开且**不会重复表头** —— 最长的审计表有 22 行，
# 一旦落在页边界，读者会看到"半张表 + 无表头"。这里把行数 ≥ MIN_ROWS 的表整体裹进
# `minipage`（不可分割），行数少的表保持原样以免影响排版。
MIN_ROWS = 12
_out: list[str] = []
_i = 0
_wrapped = 0
while _i < len(L):
    line = L[_i]
    if line == r"\begin{center}\small":
        # 找配对的 \end{center}
        _j = _i + 1
        while _j < len(L) and L[_j] != r"\end{center}":
            _j += 1
        block = L[_i + 1:_j]
        rows = sum(1 for b in block if b.endswith(r"\\"))
        if rows >= MIN_ROWS and any(b.startswith(r"\begin{tabular}") for b in block):
            _out.append(line)
            _out.append(r"\begin{minipage}{\linewidth}")
            _out.extend(block)
            _out.append(r"\end{minipage}")
            _out.append(L[_j])
            _wrapped += 1
            _i = _j + 1
            continue
    _out.append(line)
    _i += 1
L = _out
print("[后处理] %d 张 ≥%d 行的表已裹入 minipage（防跨页丢表头）" % (_wrapped, MIN_ROWS))

OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print("已写 %s（%d 行，%.1f KB）" % (OUT, len(L), OUT.stat().st_size / 1024))
